import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import {  MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid'
import {SearchIcon} from "@heroicons/react/outline"
import Footer from '../components/Footer'
import { useRef } from 'react'
import {useRouter} from "next/router"



export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null)

  const search = (e) => {
    e.preventDefault()
    const term = searchInputRef.current.value;
    if(!term) return
    router.push(`/search?term=${term}`)
  }

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google Like App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}

      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* left */}
        <div className="flex space-x-4 items-center">
          <a className="link">About</a>
          <a className="link">Store</a>
        </div>
        {/* Right */}
        <div className="flex space-x-4 items-center">
          <a className="link">Gmail</a>
          <a className="link">Images</a>

          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          {/* Avator */}
          <Avatar url="https://avatars.githubusercontent.com/u/46862628" />
        </div>

      </header>

      {/* Body */}
        <form className="flex flex-col items-center mt-44 flex-grow w-4/5" onSubmit={search}>
          <Image
            src="/google logo.png"
            width={250}
            height={175}
          />
          <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
            <SearchIcon className="h-5 mr-3 text-gray-500" />
            <input type="text" ref={searchInputRef} className="flex-grow focus:outline-none" />
            <MicrophoneIcon className="h-5" />
          </div>
          <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0  sm:flex-row sm:space-x-4">
            <button  type="submit" className="btn">Google Search</button>

            <button  type="submit" className="btn">I'm Felling Lucky</button>
          </div>
        </form>
      {/* Footer */}
      <Footer />
    </div>
  )
}
